// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9egPXkOGdkM5Rs6S7RyBYFt1t3CiLcuE',
    appId: '1:957366708477:web:24493da4cef94e51de3694',
    messagingSenderId: '957366708477',
    projectId: 'atelier4-h-nahil-iir5g2',
    authDomain: 'atelier4-h-nahil-iir5g2.firebaseapp.com',
    storageBucket: 'atelier4-h-nahil-iir5g2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW5-GwEDkf2shSZIqCMFOkS1M-qPvkw7A',
    appId: '1:957366708477:android:eef1376cd7b2b628de3694',
    messagingSenderId: '957366708477',
    projectId: 'atelier4-h-nahil-iir5g2',
    storageBucket: 'atelier4-h-nahil-iir5g2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTqvZBPQIUHbKmxjQkEqwU9J8ZhyrUQWg',
    appId: '1:957366708477:ios:9fce327777ded003de3694',
    messagingSenderId: '957366708477',
    projectId: 'atelier4-h-nahil-iir5g2',
    storageBucket: 'atelier4-h-nahil-iir5g2.appspot.com',
    iosBundleId: 'com.example.atelier4HNahilIir5g2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTqvZBPQIUHbKmxjQkEqwU9J8ZhyrUQWg',
    appId: '1:957366708477:ios:f232fbf6325f8149de3694',
    messagingSenderId: '957366708477',
    projectId: 'atelier4-h-nahil-iir5g2',
    storageBucket: 'atelier4-h-nahil-iir5g2.appspot.com',
    iosBundleId: 'com.example.atelier4HNahilIir5g2.RunnerTests',
  );
}
